#version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development            # development, production
      - FLASK_DEBUG=1                    # 1 development, 0 o nada production
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    #depends_on:
      #- redis  
    volumes:
      - .:/app                           # Volumen para sincronizar el código
    command: flask run --host=0.0.0.0    # Ejecuta la aplicación
    restart: always  
    
#redis:
    #image: "redis:latest"
    #ports:
      #- "6379:6379"                       # Asegura que el contenedor se reinicie automáticamente
